server:
  port: 8080  # ✅ Ensure Auth Service runs on this port

spring:
  application:
    name: auth-service  # ✅ This name must match what API Gateway expects

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost